name: packet_example
clean: make clean
build: make build
compile: make aiecc
run: make run
tasks:
  - name: repeat_2
    params:
      num_repeat_cores: 2
    output: build/packet_example.mlir
  - name: repeat_3
    params:
      num_repeat_cores: 3
    output: build/packet_example.mlir
  - name: repeat_4
    params:
      num_repeat_cores: 4
    output: build/packet_example.mlir
  - name: repeat_5
    params:
      num_repeat_cores: 5
    output: build/packet_example.mlir
  - name: repeat_6
    params:
      num_repeat_cores: 6
    output: build/packet_example.mlir
  - name: repeat_7
    params:
      num_repeat_cores: 7
    output: build/packet_example.mlir
  - name: repeat_8
    params:
      num_repeat_cores: 8
    output: build/packet_example.mlir
    