[node]
comp_3 = "3,0"
comp_19 = "4,3"
shim_15 = "0,3"
comp_4 = "4,0"
shim_10 = "0,2"
comp_7 = "2,1"
shim_0 = "0,0"
mem_6 = "1,1"
mem_1 = "1,0"
comp_12 = "2,2"
comp_9 = "4,1"
comp_2 = "2,0"
shim_5 = "0,1"
mem_11 = "1,2"
comp_18 = "3,3"
comp_17 = "2,3"
comp_8 = "3,1"
mem_16 = "1,3"
comp_13 = "3,2"
comp_14 = "4,2"

[edge]
5 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
4 = [ "comp_3->comp_8", [ 2, 2 ], 4 ]
31 = [ "comp_19->mem_16", [ 2, 2 ], 4 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 4 ]
9 = [ "shim_5->mem_6", [ 2, 2 ], 4 ]
22 = [ "comp_13->comp_18", [ 2, 2 ], 4 ]
18 = [ "shim_10->mem_11", [ 2, 2 ], 4 ]
11 = [ "comp_7->comp_12", [ 2, 2 ], 4 ]
12 = [ "comp_7->comp_8", [ 2, 2 ], 4 ]
29 = [ "comp_17->comp_18", [ 2, 2 ], 4 ]
15 = [ "comp_9->comp_14", [ 2, 2 ], 4 ]
13 = [ "comp_8->comp_13", [ 2, 2 ], 4 ]
14 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
32 = [ "mem_16->shim_15", [ 2, 2 ], 4 ]
26 = [ "mem_11->shim_10", [ 2, 2 ], 4 ]
19 = [ "mem_11->comp_12", [ 2, 2 ], 4 ]
16 = [ "comp_9->mem_6", [ 2, 2 ], 4 ]
8 = [ "mem_1->shim_0", [ 2, 2 ], 4 ]
28 = [ "mem_16->comp_17", [ 2, 2 ], 4 ]
0 = [ "shim_0->mem_1", [ 2, 2 ], 4 ]
17 = [ "mem_6->shim_5", [ 2, 2 ], 4 ]
7 = [ "comp_4->mem_1", [ 2, 2 ], 4 ]
10 = [ "mem_6->comp_7", [ 2, 2 ], 4 ]
27 = [ "shim_15->mem_16", [ 2, 2 ], 4 ]
20 = [ "comp_12->comp_17", [ 2, 2 ], 4 ]
21 = [ "comp_12->comp_13", [ 2, 2 ], 4 ]
23 = [ "comp_13->comp_14", [ 2, 2 ], 4 ]
24 = [ "comp_14->comp_19", [ 2, 2 ], 4 ]
2 = [ "comp_2->comp_7", [ 2, 2 ], 4 ]
25 = [ "comp_14->mem_11", [ 2, 2 ], 4 ]
6 = [ "comp_4->comp_9", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
30 = [ "comp_18->comp_19", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_2 = "9->10"
link_3 = "16->17"
link_6 = "27->28"
link_1 = "7->8"
link_4 = "18->19"
link_5 = "25->26"
link_7 = "31->32"

[route]
5 = [ "neighbor_sharing", { comp_4 = [ "4,0" ] } ]
4 = [ "neighbor_sharing", { comp_8 = [ "3,0" ] } ]
31 = [ "circuit_switch", { mem_16 = [ "4,3", "3,3", "2,3", "1,3" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
9 = [ "circuit_switch", { mem_6 = [ "0,1", "1,1" ] } ]
22 = [ "neighbor_sharing", { comp_18 = [ "3,2" ] } ]
18 = [ "circuit_switch", { mem_11 = [ "0,2", "1,2" ] } ]
11 = [ "neighbor_sharing", { comp_12 = [ "2,1" ] } ]
12 = [ "neighbor_sharing", { comp_8 = [ "3,1" ] } ]
29 = [ "neighbor_sharing", { comp_18 = [ "2,3" ] } ]
15 = [ "neighbor_sharing", { comp_14 = [ "4,1" ] } ]
13 = [ "neighbor_sharing", { comp_13 = [ "3,1" ] } ]
14 = [ "neighbor_sharing", { comp_9 = [ "3,1" ] } ]
32 = [ "circuit_switch", { shim_15 = [ "1,3", "0,3" ] } ]
26 = [ "circuit_switch", { shim_10 = [ "1,2", "0,2" ] } ]
19 = [ "circuit_switch", { comp_12 = [ "1,2", "2,2" ] } ]
16 = [ "circuit_switch", { mem_6 = [ "4,1", "3,1", "2,1", "1,1" ] } ]
8 = [ "circuit_switch", { shim_0 = [ "1,0", "0,0" ] } ]
28 = [ "circuit_switch", { comp_17 = [ "1,3", "2,3" ] } ]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
17 = [ "circuit_switch", { shim_5 = [ "1,1", "0,1" ] } ]
7 = [ "circuit_switch", { mem_1 = [ "4,0", "3,0", "2,0", "1,0" ] } ]
10 = [ "circuit_switch", { comp_7 = [ "1,1", "2,1" ] } ]
27 = [ "circuit_switch", { mem_16 = [ "0,3", "1,3" ] } ]
20 = [ "neighbor_sharing", { comp_17 = [ "2,2" ] } ]
21 = [ "neighbor_sharing", { comp_13 = [ "2,2" ] } ]
23 = [ "neighbor_sharing", { comp_14 = [ "3,2" ] } ]
24 = [ "neighbor_sharing", { comp_19 = [ "4,2" ] } ]
2 = [ "neighbor_sharing", { comp_7 = [ "2,0" ] } ]
25 = [ "circuit_switch", { mem_11 = [ "4,2", "3,2", "2,2", "1,2" ] } ]
6 = [ "neighbor_sharing", { comp_9 = [ "4,0" ] } ]
3 = [ "neighbor_sharing", { comp_3 = [ "3,0" ] } ]
30 = [ "neighbor_sharing", { comp_19 = [ "4,3" ] } ]
