[node]
mem_7 = "1,1"
shim_6 = "0,1"
comp_2 = "2,0"
mem_1 = "1,0"
shim_0 = "0,0"
comp_3 = "3,0"
comp_9 = "3,1"
comp_4 = "4,0"
comp_10 = "4,1"
comp_8 = "2,1"
comp_5 = "5,0"
comp_11 = "5,1"

[edge]
4 = [ "comp_3->comp_9", [ 2, 2 ], 4 ]
2 = [ "comp_2->comp_8", [ 2, 2 ], 4 ]
17 = [ "mem_7->shim_6", [ 2, 2 ], 4 ]
7 = [ "comp_4->comp_5", [ 2, 2 ], 4 ]
8 = [ "comp_5->comp_11", [ 2, 2 ], 4 ]
6 = [ "comp_4->comp_10", [ 2, 2 ], 4 ]
5 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
16 = [ "comp_11->mem_7", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
10 = [ "mem_1->shim_0", [ 2, 2 ], 4 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 4 ]
0 = [ "shim_0->mem_1", [ 2, 2 ], 4 ]
9 = [ "comp_5->mem_1", [ 2, 2 ], 4 ]
11 = [ "shim_6->mem_7", [ 2, 2 ], 4 ]
12 = [ "mem_7->comp_8", [ 2, 2 ], 4 ]
15 = [ "comp_10->comp_11", [ 2, 2 ], 4 ]
13 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
14 = [ "comp_9->comp_10", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_2 = "11->12"
link_3 = "16->17"
link_1 = "9->10"

[route]
4 = [ "neighbor_sharing", { comp_9 = [ "3,0" ] } ]
2 = [ "neighbor_sharing", { comp_8 = [ "2,0" ] } ]
17 = [ "circuit_switch", { shim_6 = [ "1,1", "0,1" ] } ]
7 = [ "neighbor_sharing", { comp_5 = [ "5,0" ] } ]
8 = [ "neighbor_sharing", { comp_11 = [ "5,0" ] } ]
6 = [ "neighbor_sharing", { comp_10 = [ "4,0" ] } ]
5 = [ "neighbor_sharing", { comp_4 = [ "4,0" ] } ]
16 = [ "circuit_switch", { mem_7 = [ "5,1", "4,1", "3,1", "2,1", "1,1" ] } ]
3 = [ "neighbor_sharing", { comp_3 = [ "2,0" ] } ]
10 = [ "circuit_switch", { shim_0 = [ "1,0", "0,0" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
9 = [ "circuit_switch", { mem_1 = [ "5,0", "4,0", "3,0", "2,0", "1,0" ] } ]
11 = [ "circuit_switch", { mem_7 = [ "0,1", "1,1" ] } ]
12 = [ "circuit_switch", { comp_8 = [ "1,1", "2,1" ] } ]
15 = [ "neighbor_sharing", { comp_11 = [ "4,1" ] } ]
13 = [ "neighbor_sharing", { comp_9 = [ "2,1" ] } ]
14 = [ "neighbor_sharing", { comp_10 = [ "3,1" ] } ]
