[node]
shim_10 = "0,2"
comp_14 = "4,2"
comp_4 = "4,0"
comp_27 = "2,5"
shim_15 = "0,3"
comp_18 = "3,3"
mem_16 = "1,3"
mem_11 = "1,2"
mem_26 = "1,5"
comp_2 = "2,0"
mem_6 = "1,1"
mem_1 = "1,0"
comp_8 = "3,1"
comp_13 = "3,2"
comp_29 = "4,5"
comp_19 = "4,3"
comp_22 = "2,4"
comp_3 = "3,0"
comp_28 = "3,5"
comp_23 = "3,4"
comp_7 = "2,1"
shim_25 = "0,5"
shim_5 = "0,1"
comp_24 = "4,4"
comp_12 = "2,2"
shim_0 = "0,0"
shim_20 = "0,4"
mem_21 = "1,4"
comp_17 = "2,3"
comp_9 = "4,1"

[edge]
34 = [ "mem_21->shim_20", [ 2, 2 ], 4 ]
14 = [ "comp_3->comp_9", [ 2, 2 ], 4 ]
33 = [ "comp_24->mem_21", [ 2, 2 ], 4 ]
31 = [ "comp_19->mem_16", [ 2, 2 ], 4 ]
32 = [ "mem_16->shim_15", [ 2, 2 ], 4 ]
26 = [ "mem_1->shim_0", [ 2, 2 ], 4 ]
11 = [ "comp_22->comp_23", [ 2, 2 ], 4 ]
18 = [ "comp_13->comp_29", [ 2, 2 ], 4 ]
12 = [ "comp_27->comp_28", [ 2, 2 ], 4 ]
29 = [ "comp_14->mem_11", [ 2, 2 ], 4 ]
15 = [ "comp_3->comp_14", [ 2, 2 ], 4 ]
13 = [ "comp_27->comp_4", [ 2, 2 ], 4 ]
19 = [ "comp_18->mem_16", [ 2, 2 ], 4 ]
30 = [ "mem_11->shim_10", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_12", [ 2, 2 ], 4 ]
6 = [ "comp_12->comp_27", [ 2, 2 ], 4 ]
4 = [ "comp_7->comp_17", [ 2, 2 ], 4 ]
5 = [ "comp_7->comp_22", [ 2, 2 ], 4 ]
16 = [ "comp_8->comp_19", [ 2, 2 ], 4 ]
8 = [ "comp_17->comp_8", [ 2, 2 ], 4 ]
28 = [ "mem_6->shim_5", [ 2, 2 ], 4 ]
9 = [ "comp_17->comp_13", [ 2, 2 ], 4 ]
17 = [ "comp_8->comp_24", [ 2, 2 ], 4 ]
0 = [ "shim_0->mem_1", [ 2, 2 ], 4 ]
22 = [ "mem_21->shim_20", [ 2, 2 ], 4 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 4 ]
36 = [ "mem_26->shim_25", [ 2, 2 ], 4 ]
7 = [ "comp_12->comp_3", [ 2, 2 ], 4 ]
10 = [ "comp_22->comp_18", [ 2, 2 ], 4 ]
27 = [ "comp_9->mem_6", [ 2, 2 ], 4 ]
35 = [ "comp_29->mem_26", [ 2, 2 ], 4 ]
20 = [ "mem_16->shim_15", [ 2, 2 ], 4 ]
21 = [ "comp_23->mem_21", [ 2, 2 ], 4 ]
23 = [ "comp_28->mem_26", [ 2, 2 ], 4 ]
24 = [ "mem_26->shim_25", [ 2, 2 ], 4 ]
2 = [ "comp_2->comp_7", [ 2, 2 ], 4 ]
25 = [ "comp_4->mem_1", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_2 = "21->22"
link_3 = "23->24"
link_6 = "29->30"
link_1 = "19->20"
link_8 = "33->34"
link_4 = "25->26"
link_5 = "27->28"
link_7 = "31->32"
link_9 = "35->36"

[route]
34 = [ "circuit_switch", { shim_20 = [ "1,4", "0,4" ] } ]
14 = [ "circuit_switch", { comp_9 = [ "3,0", "4,0", "4,1" ] } ]
33 = [ "circuit_switch", { mem_21 = [ "4,4", "3,4", "2,4", "1,4" ] } ]
31 = [ "circuit_switch", { mem_16 = [ "4,3", "3,3", "2,3", "1,3" ] } ]
32 = [ "circuit_switch", { shim_15 = [ "1,3", "0,3" ] } ]
26 = [ "circuit_switch", { shim_0 = [ "1,0", "0,0" ] } ]
11 = [ "neighbor_sharing", { comp_23 = [ "2,4" ] } ]
18 = [ "circuit_switch", { comp_29 = [ "3,2", "3,3", "3,4", "3,5", "4,5" ] } ]
12 = [ "neighbor_sharing", { comp_28 = [ "2,5" ] } ]
29 = [ "circuit_switch", { mem_11 = [ "4,2", "3,2", "2,2", "1,2" ] } ]
15 = [ "circuit_switch", { comp_14 = [ "3,0", "3,1", "3,2", "4,2" ] } ]
13 = [ "circuit_switch", { comp_4 = [ "2,5", "2,4", "2,3", "2,2", "2,1", "2,0", "3,0", "4,0" ] } ]
19 = [ "circuit_switch", { mem_16 = [ "3,3", "2,3", "1,3" ] } ]
30 = [ "circuit_switch", { shim_10 = [ "1,2", "0,2" ] } ]
3 = [ "circuit_switch", { comp_12 = [ "2,0", "2,1", "2,2" ] } ]
6 = [ "circuit_switch", { comp_27 = [ "2,2", "2,3", "2,4", "2,5" ] } ]
4 = [ "circuit_switch", { comp_17 = [ "2,1", "2,2", "2,3" ] } ]
5 = [ "circuit_switch", { comp_22 = [ "2,1", "2,2", "2,3", "2,4" ] } ]
16 = [ "circuit_switch", { comp_19 = [ "3,1", "3,2", "4,2", "4,3" ] } ]
8 = [ "circuit_switch", { comp_8 = [ "2,3", "3,3", "3,2", "3,1" ] } ]
28 = [ "circuit_switch", { shim_5 = [ "1,1", "0,1" ] } ]
9 = [ "circuit_switch", { comp_13 = [ "2,3", "2,2", "3,2" ] } ]
17 = [ "circuit_switch", { comp_24 = [ "3,1", "3,2", "3,3", "3,4", "4,4" ] } ]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
22 = [ "circuit_switch", { shim_20 = [ "1,4", "0,4" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
36 = [ "circuit_switch", { shim_25 = [ "1,5", "0,5" ] } ]
7 = [ "circuit_switch", { comp_3 = [ "2,2", "2,1", "2,0", "3,0" ] } ]
10 = [ "circuit_switch", { comp_18 = [ "2,4", "2,3", "3,3" ] } ]
27 = [ "circuit_switch", { mem_6 = [ "4,1", "3,1", "2,1", "1,1" ] } ]
35 = [ "circuit_switch", { mem_26 = [ "4,5", "3,5", "2,5", "1,5" ] } ]
20 = [ "circuit_switch", { shim_15 = [ "1,3", "0,3" ] } ]
21 = [ "circuit_switch", { mem_21 = [ "3,4", "2,4", "1,4" ] } ]
23 = [ "circuit_switch", { mem_26 = [ "3,5", "2,5", "1,5" ] } ]
24 = [ "circuit_switch", { shim_25 = [ "1,5", "0,5" ] } ]
2 = [ "neighbor_sharing", { comp_7 = [ "2,0" ] } ]
25 = [ "circuit_switch", { mem_1 = [ "4,0", "3,0", "2,0", "1,0" ] } ]
