[node]
comp_34 = "4,6"
comp_29 = "4,5"
shim_20 = "0,4"
mem_21 = "1,4"
comp_28 = "3,5"
comp_8 = "3,1"
mem_16 = "1,3"
comp_38 = "3,7"
comp_13 = "3,2"
comp_4 = "4,0"
comp_27 = "2,5"
comp_39 = "4,7"
mem_36 = "1,7"
shim_0 = "0,0"
shim_35 = "0,7"
mem_26 = "1,5"
comp_2 = "2,0"
mem_11 = "1,2"
mem_1 = "1,0"
comp_37 = "2,7"
mem_6 = "1,1"
comp_23 = "3,4"
shim_30 = "0,6"
mem_31 = "1,6"
comp_32 = "2,6"
shim_25 = "0,5"
comp_7 = "2,1"
comp_22 = "2,4"
comp_19 = "4,3"
comp_3 = "3,0"
shim_5 = "0,1"
comp_24 = "4,4"
comp_12 = "2,2"
comp_33 = "3,6"
comp_14 = "4,2"
shim_10 = "0,2"
comp_9 = "4,1"
comp_17 = "2,3"
shim_15 = "0,3"
comp_18 = "3,3"

[edge]
60 = [ "comp_34->comp_39", [ 2, 2 ], 4 ]
59 = [ "comp_33->comp_34", [ 2, 2 ], 4 ]
50 = [ "comp_28->comp_29", [ 2, 2 ], 4 ]
67 = [ "comp_39->mem_36", [ 2, 2 ], 4 ]
54 = [ "shim_30->mem_31", [ 2, 2 ], 4 ]
52 = [ "comp_29->mem_26", [ 2, 2 ], 4 ]
51 = [ "comp_29->comp_34", [ 2, 2 ], 4 ]
5 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
61 = [ "comp_34->mem_31", [ 2, 2 ], 4 ]
38 = [ "comp_22->comp_27", [ 2, 2 ], 4 ]
40 = [ "comp_23->comp_28", [ 2, 2 ], 4 ]
0 = [ "shim_0->mem_1", [ 2, 2 ], 4 ]
17 = [ "mem_6->shim_5", [ 2, 2 ], 4 ]
35 = [ "mem_16->shim_15", [ 2, 2 ], 4 ]
8 = [ "mem_1->shim_0", [ 2, 2 ], 4 ]
20 = [ "comp_12->comp_17", [ 2, 2 ], 4 ]
23 = [ "comp_13->comp_14", [ 2, 2 ], 4 ]
24 = [ "comp_14->comp_19", [ 2, 2 ], 4 ]
2 = [ "comp_2->comp_7", [ 2, 2 ], 4 ]
25 = [ "comp_14->mem_11", [ 2, 2 ], 4 ]
58 = [ "comp_33->comp_38", [ 2, 2 ], 4 ]
30 = [ "comp_17->comp_18", [ 2, 2 ], 4 ]
22 = [ "comp_13->comp_18", [ 2, 2 ], 4 ]
9 = [ "shim_5->mem_6", [ 2, 2 ], 4 ]
66 = [ "comp_38->comp_39", [ 2, 2 ], 4 ]
19 = [ "mem_11->comp_12", [ 2, 2 ], 4 ]
7 = [ "comp_4->mem_1", [ 2, 2 ], 4 ]
65 = [ "comp_37->comp_38", [ 2, 2 ], 4 ]
63 = [ "shim_35->mem_36", [ 2, 2 ], 4 ]
64 = [ "mem_36->comp_37", [ 2, 2 ], 4 ]
34 = [ "comp_19->mem_16", [ 2, 2 ], 4 ]
14 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
21 = [ "comp_12->comp_13", [ 2, 2 ], 4 ]
26 = [ "mem_11->shim_10", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
62 = [ "mem_31->shim_30", [ 2, 2 ], 4 ]
55 = [ "mem_31->comp_32", [ 2, 2 ], 4 ]
68 = [ "mem_36->shim_35", [ 2, 2 ], 4 ]
6 = [ "comp_4->comp_9", [ 2, 2 ], 4 ]
33 = [ "comp_19->comp_24", [ 2, 2 ], 4 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 4 ]
36 = [ "shim_20->mem_21", [ 2, 2 ], 4 ]
18 = [ "shim_10->mem_11", [ 2, 2 ], 4 ]
11 = [ "comp_7->comp_12", [ 2, 2 ], 4 ]
39 = [ "comp_22->comp_23", [ 2, 2 ], 4 ]
45 = [ "shim_25->mem_26", [ 2, 2 ], 4 ]
31 = [ "comp_18->comp_23", [ 2, 2 ], 4 ]
57 = [ "comp_32->comp_33", [ 2, 2 ], 4 ]
12 = [ "comp_7->comp_8", [ 2, 2 ], 4 ]
10 = [ "mem_6->comp_7", [ 2, 2 ], 4 ]
27 = [ "shim_15->mem_16", [ 2, 2 ], 4 ]
44 = [ "mem_21->shim_20", [ 2, 2 ], 4 ]
29 = [ "comp_17->comp_22", [ 2, 2 ], 4 ]
56 = [ "comp_32->comp_37", [ 2, 2 ], 4 ]
15 = [ "comp_9->comp_14", [ 2, 2 ], 4 ]
13 = [ "comp_8->comp_13", [ 2, 2 ], 4 ]
32 = [ "comp_18->comp_19", [ 2, 2 ], 4 ]
16 = [ "comp_9->mem_6", [ 2, 2 ], 4 ]
43 = [ "comp_24->mem_21", [ 2, 2 ], 4 ]
47 = [ "comp_27->comp_32", [ 2, 2 ], 4 ]
28 = [ "mem_16->comp_17", [ 2, 2 ], 4 ]
41 = [ "comp_23->comp_24", [ 2, 2 ], 4 ]
53 = [ "mem_26->shim_25", [ 2, 2 ], 4 ]
4 = [ "comp_3->comp_8", [ 2, 2 ], 4 ]
42 = [ "comp_24->comp_29", [ 2, 2 ], 4 ]
49 = [ "comp_28->comp_33", [ 2, 2 ], 4 ]
37 = [ "mem_21->comp_22", [ 2, 2 ], 4 ]
46 = [ "mem_26->comp_27", [ 2, 2 ], 4 ]
48 = [ "comp_27->comp_28", [ 2, 2 ], 4 ]

[linking]
link_15 = "67->68"
link_13 = "61->62"
link_9 = "43->44"
link_8 = "36->37"
link_7 = "34->35"
link_0 = "0->1"
link_2 = "9->10"
link_3 = "16->17"
link_6 = "27->28"
link_1 = "7->8"
link_11 = "52->53"
link_4 = "18->19"
link_14 = "63->64"
link_5 = "25->26"
link_12 = "54->55"
link_10 = "45->46"

[route]
60 = [ "neighbor_sharing", { comp_39 = [ "4,6" ] } ]
59 = [ "neighbor_sharing", { comp_34 = [ "3,6" ] } ]
50 = [ "neighbor_sharing", { comp_29 = [ "3,5" ] } ]
67 = [ "circuit_switch", { mem_36 = [ "4,7", "3,7", "2,7", "1,7" ] } ]
54 = [ "circuit_switch", { mem_31 = [ "0,6", "1,6" ] } ]
52 = [ "circuit_switch", { mem_26 = [ "4,5", "3,5", "2,5", "1,5" ] } ]
51 = [ "neighbor_sharing", { comp_34 = [ "4,5" ] } ]
5 = [ "neighbor_sharing", { comp_4 = [ "3,0" ] } ]
61 = [ "circuit_switch", { mem_31 = [ "4,6", "3,6", "2,6", "1,6" ] } ]
38 = [ "neighbor_sharing", { comp_27 = [ "2,4" ] } ]
40 = [ "neighbor_sharing", { comp_28 = [ "3,4" ] } ]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
17 = [ "circuit_switch", { shim_5 = [ "1,1", "0,1" ] } ]
35 = [ "circuit_switch", { shim_15 = [ "1,3", "0,3" ] } ]
8 = [ "circuit_switch", { shim_0 = [ "1,0", "0,0" ] } ]
20 = [ "neighbor_sharing", { comp_17 = [ "2,2" ] } ]
23 = [ "neighbor_sharing", { comp_14 = [ "3,2" ] } ]
24 = [ "neighbor_sharing", { comp_19 = [ "4,2" ] } ]
2 = [ "neighbor_sharing", { comp_7 = [ "2,0" ] } ]
25 = [ "circuit_switch", { mem_11 = [ "4,2", "3,2", "2,2", "1,2" ] } ]
58 = [ "neighbor_sharing", { comp_38 = [ "3,6" ] } ]
30 = [ "neighbor_sharing", { comp_18 = [ "2,3" ] } ]
22 = [ "neighbor_sharing", { comp_18 = [ "3,2" ] } ]
9 = [ "circuit_switch", { mem_6 = [ "0,1", "1,1" ] } ]
66 = [ "neighbor_sharing", { comp_39 = [ "3,7" ] } ]
19 = [ "circuit_switch", { comp_12 = [ "1,2", "2,2" ] } ]
7 = [ "circuit_switch", { mem_1 = [ "4,0", "3,0", "2,0", "1,0" ] } ]
65 = [ "neighbor_sharing", { comp_38 = [ "2,7" ] } ]
63 = [ "circuit_switch", { mem_36 = [ "0,7", "1,7" ] } ]
64 = [ "circuit_switch", { comp_37 = [ "1,7", "2,7" ] } ]
34 = [ "circuit_switch", { mem_16 = [ "4,3", "3,3", "2,3", "1,3" ] } ]
14 = [ "neighbor_sharing", { comp_9 = [ "3,1" ] } ]
21 = [ "neighbor_sharing", { comp_13 = [ "2,2" ] } ]
26 = [ "circuit_switch", { shim_10 = [ "1,2", "0,2" ] } ]
3 = [ "neighbor_sharing", { comp_3 = [ "2,0" ] } ]
62 = [ "circuit_switch", { shim_30 = [ "1,6", "0,6" ] } ]
55 = [ "circuit_switch", { comp_32 = [ "1,6", "2,6" ] } ]
68 = [ "circuit_switch", { shim_35 = [ "1,7", "0,7" ] } ]
6 = [ "neighbor_sharing", { comp_9 = [ "4,0" ] } ]
33 = [ "neighbor_sharing", { comp_24 = [ "4,3" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
36 = [ "circuit_switch", { mem_21 = [ "0,4", "1,4" ] } ]
18 = [ "circuit_switch", { mem_11 = [ "0,2", "1,2" ] } ]
11 = [ "neighbor_sharing", { comp_12 = [ "2,1" ] } ]
39 = [ "neighbor_sharing", { comp_23 = [ "2,4" ] } ]
45 = [ "circuit_switch", { mem_26 = [ "0,5", "1,5" ] } ]
31 = [ "neighbor_sharing", { comp_23 = [ "3,3" ] } ]
57 = [ "neighbor_sharing", { comp_33 = [ "2,6" ] } ]
12 = [ "neighbor_sharing", { comp_8 = [ "2,1" ] } ]
10 = [ "circuit_switch", { comp_7 = [ "1,1", "2,1" ] } ]
27 = [ "circuit_switch", { mem_16 = [ "0,3", "1,3" ] } ]
44 = [ "circuit_switch", { shim_20 = [ "1,4", "0,4" ] } ]
29 = [ "neighbor_sharing", { comp_22 = [ "2,3" ] } ]
56 = [ "neighbor_sharing", { comp_37 = [ "2,6" ] } ]
15 = [ "neighbor_sharing", { comp_14 = [ "4,1" ] } ]
13 = [ "neighbor_sharing", { comp_13 = [ "3,1" ] } ]
32 = [ "neighbor_sharing", { comp_19 = [ "3,3" ] } ]
16 = [ "circuit_switch", { mem_6 = [ "4,1", "3,1", "2,1", "1,1" ] } ]
43 = [ "circuit_switch", { mem_21 = [ "4,4", "3,4", "2,4", "1,4" ] } ]
47 = [ "neighbor_sharing", { comp_32 = [ "2,5" ] } ]
28 = [ "circuit_switch", { comp_17 = [ "1,3", "2,3" ] } ]
41 = [ "neighbor_sharing", { comp_24 = [ "3,4" ] } ]
53 = [ "circuit_switch", { shim_25 = [ "1,5", "0,5" ] } ]
4 = [ "neighbor_sharing", { comp_8 = [ "3,0" ] } ]
42 = [ "neighbor_sharing", { comp_29 = [ "4,4" ] } ]
49 = [ "neighbor_sharing", { comp_33 = [ "3,5" ] } ]
37 = [ "circuit_switch", { comp_22 = [ "1,4", "2,4" ] } ]
46 = [ "circuit_switch", { comp_27 = [ "1,5", "2,5" ] } ]
48 = [ "neighbor_sharing", { comp_28 = [ "2,5" ] } ]
