[node]
comp_29 = "5,4"
comp_10 = "4,1"
comp_28 = "4,4"
comp_2 = "2,0"
mem_25 = "1,4"
shim_24 = "0,4"
mem_31 = "1,5"
comp_5 = "5,0"
shim_12 = "0,2"
mem_1 = "1,0"
comp_16 = "4,2"
mem_13 = "1,2"
comp_15 = "3,2"
comp_21 = "3,3"
shim_30 = "0,5"
comp_23 = "5,3"
comp_8 = "2,1"
comp_26 = "2,4"
shim_18 = "0,3"
shim_6 = "0,1"
comp_20 = "2,3"
comp_4 = "4,0"
shim_0 = "0,0"
comp_34 = "4,5"
mem_19 = "1,3"
mem_7 = "1,1"
comp_11 = "5,1"
comp_9 = "3,1"
comp_17 = "5,2"
comp_35 = "5,5"
comp_3 = "3,0"
comp_22 = "4,3"
comp_32 = "2,5"
comp_14 = "2,2"
comp_33 = "3,5"
comp_27 = "3,4"

[edge]
34 = [ "mem_25->shim_24", [ 2, 2 ], 4 ]
14 = [ "comp_3->comp_10", [ 2, 2 ], 4 ]
33 = [ "comp_28->mem_25", [ 2, 2 ], 4 ]
31 = [ "comp_22->mem_19", [ 2, 2 ], 4 ]
32 = [ "mem_19->shim_18", [ 2, 2 ], 4 ]
26 = [ "mem_1->shim_0", [ 2, 2 ], 4 ]
30 = [ "mem_13->shim_12", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_14", [ 2, 2 ], 4 ]
45 = [ "comp_29->mem_25", [ 2, 2 ], 4 ]
6 = [ "comp_14->comp_32", [ 2, 2 ], 4 ]
25 = [ "comp_4->mem_1", [ 2, 2 ], 4 ]
2 = [ "comp_2->comp_8", [ 2, 2 ], 4 ]
24 = [ "comp_33->comp_35", [ 2, 2 ], 4 ]
23 = [ "comp_27->comp_29", [ 2, 2 ], 4 ]
21 = [ "comp_21->comp_17", [ 2, 2 ], 4 ]
20 = [ "comp_21->comp_11", [ 2, 2 ], 4 ]
27 = [ "comp_10->mem_7", [ 2, 2 ], 4 ]
35 = [ "comp_34->mem_31", [ 2, 2 ], 4 ]
10 = [ "comp_26->comp_21", [ 2, 2 ], 4 ]
7 = [ "comp_14->comp_3", [ 2, 2 ], 4 ]
42 = [ "mem_13->shim_12", [ 2, 2 ], 4 ]
19 = [ "comp_15->comp_5", [ 2, 2 ], 4 ]
37 = [ "comp_5->mem_1", [ 2, 2 ], 4 ]
38 = [ "mem_1->shim_0", [ 2, 2 ], 4 ]
8 = [ "comp_20->comp_9", [ 2, 2 ], 4 ]
4 = [ "comp_8->comp_20", [ 2, 2 ], 4 ]
43 = [ "comp_23->mem_19", [ 2, 2 ], 4 ]
5 = [ "comp_8->comp_26", [ 2, 2 ], 4 ]
46 = [ "mem_25->shim_24", [ 2, 2 ], 4 ]
41 = [ "comp_17->mem_13", [ 2, 2 ], 4 ]
28 = [ "mem_7->shim_6", [ 2, 2 ], 4 ]
48 = [ "mem_31->shim_30", [ 2, 2 ], 4 ]
18 = [ "comp_15->comp_34", [ 2, 2 ], 4 ]
9 = [ "comp_20->comp_15", [ 2, 2 ], 4 ]
36 = [ "mem_31->shim_30", [ 2, 2 ], 4 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 4 ]
22 = [ "comp_27->comp_23", [ 2, 2 ], 4 ]
47 = [ "comp_35->mem_31", [ 2, 2 ], 4 ]
16 = [ "comp_9->comp_22", [ 2, 2 ], 4 ]
13 = [ "comp_32->comp_4", [ 2, 2 ], 4 ]
15 = [ "comp_3->comp_16", [ 2, 2 ], 4 ]
29 = [ "comp_16->mem_13", [ 2, 2 ], 4 ]
17 = [ "comp_9->comp_28", [ 2, 2 ], 4 ]
0 = [ "shim_0->mem_1", [ 2, 2 ], 4 ]
40 = [ "mem_7->shim_6", [ 2, 2 ], 4 ]
44 = [ "mem_19->shim_18", [ 2, 2 ], 4 ]
12 = [ "comp_32->comp_33", [ 2, 2 ], 4 ]
11 = [ "comp_26->comp_27", [ 2, 2 ], 4 ]
39 = [ "comp_11->mem_7", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_2 = "27->28"
link_3 = "29->30"
link_6 = "35->36"
link_1 = "25->26"
link_8 = "39->40"
link_10 = "43->44"
link_11 = "45->46"
link_4 = "31->32"
link_12 = "47->48"
link_7 = "37->38"
link_5 = "33->34"
link_9 = "41->42"

[route]
34 = [ "circuit_switch", { shim_24 = [ "1,4", "0,4" ] } ]
14 = [ "circuit_switch", { comp_10 = [ "3,0", "4,0", "4,1" ] } ]
33 = [ "circuit_switch", { mem_25 = [ "4,4", "3,4", "2,4", "1,4" ] } ]
31 = [ "circuit_switch", { mem_19 = [ "4,3", "3,3", "2,3", "1,3" ] } ]
32 = [ "circuit_switch", { shim_18 = [ "1,3", "0,3" ] } ]
26 = [ "circuit_switch", { shim_0 = [ "1,0", "0,0" ] } ]
30 = [ "circuit_switch", { shim_12 = [ "1,2", "0,2" ] } ]
3 = [ "circuit_switch", { comp_14 = [ "2,0", "2,1", "2,2" ] } ]
45 = [ "circuit_switch", { mem_25 = [ "5,4", "4,4", "3,4", "2,4", "1,4" ] } ]
6 = [ "circuit_switch", { comp_32 = [ "2,2", "2,3", "2,4", "2,5" ] } ]
25 = [ "circuit_switch", { mem_1 = [ "4,0", "3,0", "2,0", "1,0" ] } ]
2 = [ "neighbor_sharing", { comp_8 = [ "2,0" ] } ]
24 = [ "circuit_switch", { comp_35 = [ "3,5", "4,5", "5,5" ] } ]
23 = [ "circuit_switch", { comp_29 = [ "3,4", "4,4", "5,4" ] } ]
21 = [ "circuit_switch", { comp_17 = [ "3,3", "3,2", "4,2", "5,2" ] } ]
20 = [ "circuit_switch", { comp_11 = [ "3,3", "4,3", "4,2", "5,2", "5,1" ] } ]
27 = [ "circuit_switch", { mem_7 = [ "4,1", "3,1", "2,1", "1,1" ] } ]
35 = [ "circuit_switch", { mem_31 = [ "4,5", "3,5", "2,5", "1,5" ] } ]
10 = [ "circuit_switch", { comp_21 = [ "2,4", "2,3", "3,3" ] } ]
7 = [ "circuit_switch", { comp_3 = [ "2,2", "2,1", "3,1", "3,0" ] } ]
42 = [ "circuit_switch", { shim_12 = [ "1,2", "0,2" ] } ]
19 = [ "circuit_switch", { comp_5 = [ "3,2", "4,2", "4,1", "5,1", "5,0" ] } ]
37 = [ "circuit_switch", { mem_1 = [ "5,0", "4,0", "3,0", "2,0", "1,0" ] } ]
38 = [ "circuit_switch", { shim_0 = [ "1,0", "0,0" ] } ]
8 = [ "circuit_switch", { comp_9 = [ "2,3", "3,3", "3,2", "3,1" ] } ]
4 = [ "circuit_switch", { comp_20 = [ "2,1", "2,2", "2,3" ] } ]
43 = [ "circuit_switch", { mem_19 = [ "5,3", "4,3", "3,3", "2,3", "1,3" ] } ]
5 = [ "circuit_switch", { comp_26 = [ "2,1", "2,2", "2,3", "2,4" ] } ]
46 = [ "circuit_switch", { shim_24 = [ "1,4", "0,4" ] } ]
41 = [ "circuit_switch", { mem_13 = [ "5,2", "4,2", "3,2", "2,2", "1,2" ] } ]
28 = [ "circuit_switch", { shim_6 = [ "1,1", "0,1" ] } ]
48 = [ "circuit_switch", { shim_30 = [ "1,5", "0,5" ] } ]
18 = [ "circuit_switch", { comp_34 = [ "3,2", "4,2", "4,3", "4,4", "4,5" ] } ]
9 = [ "circuit_switch", { comp_15 = [ "2,3", "3,3", "3,2" ] } ]
36 = [ "circuit_switch", { shim_30 = [ "1,5", "0,5" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
22 = [ "circuit_switch", { comp_23 = [ "3,4", "3,3", "4,3", "5,3" ] } ]
47 = [ "circuit_switch", { mem_31 = [ "5,5", "4,5", "3,5", "2,5", "1,5" ] } ]
16 = [ "circuit_switch", { comp_22 = [ "3,1", "3,2", "4,2", "4,3" ] } ]
13 = [ "circuit_switch", { comp_4 = [ "2,5", "3,5", "3,4", "3,3", "3,2", "3,1", "4,1", "4,0" ] } ]
15 = [ "circuit_switch", { comp_16 = [ "3,0", "4,0", "4,1", "4,2" ] } ]
29 = [ "circuit_switch", { mem_13 = [ "4,2", "3,2", "2,2", "1,2" ] } ]
17 = [ "circuit_switch", { comp_28 = [ "3,1", "3,2", "3,3", "4,3", "4,4" ] } ]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
40 = [ "circuit_switch", { shim_6 = [ "1,1", "0,1" ] } ]
44 = [ "circuit_switch", { shim_18 = [ "1,3", "0,3" ] } ]
12 = [ "neighbor_sharing", { comp_33 = [ "2,5" ] } ]
11 = [ "neighbor_sharing", { comp_27 = [ "2,4" ] } ]
39 = [ "circuit_switch", { mem_7 = [ "5,1", "4,1", "3,1", "2,1", "1,1" ] } ]
