name: Vector Scalar Multiplication
clean: make clean
build: make
run: make run
tasks:
  - name: default
    params:
      TODO: TODO
    output: build/aie_in1_size.mlir # TODO: filename in Makefile should be fixed