name: LLaMA Multi-Head Attention
clean: make clean
build: make
run: make run
tasks:
  - name: GEMM_R6_C8
    params:
      n_aie_cols: 8
    output: build/aie_512x512x512_32x32x32_8c.mlir
  - name: GEMM_R6_C4
    params:
      n_aie_cols: 4
    output: build/aie_512x512x512_32x32x32_8c.mlir
  - name: GEMM_R6_C2
    params:
      n_aie_cols: 2
    output: build/aie_512x512x512_32x32x32_8c.mlir
  - name: GEMM_R6_C1
    params:
      n_aie_cols: 1
    output: build/aie_512x512x512_32x32x32_8c.mlir