[node]
comp_12 = "3,5"
mem_17 = "1,6"
comp_3 = "2,3"
comp_2 = "2,2"
comp_5 = "2,5"
comp_8 = "3,1"
comp_0 = "2,0"
comp_4 = "2,4"
comp_9 = "3,2"
shim_15 = "0,6"
comp_10 = "3,3"
mem_16 = "1,0"
comp_11 = "3,4"
shim_14 = "0,0"
comp_6 = "2,6"
comp_1 = "2,1"
comp_7 = "3,0"
comp_13 = "3,6"

[edge]
5 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
4 = [ "comp_2->comp_9", [ 2, 2 ], 4 ]
31 = [ "mem_17->shim_15", [ 2, 2 ], 4 ]
18 = [ "comp_9->comp_2", [ 2, 2 ], 4 ]
11 = [ "comp_5->comp_6", [ 2, 2 ], 4 ]
12 = [ "comp_6->comp_13", [ 2, 2 ], 4 ]
29 = [ "mem_16->comp_7", [ 2, 2 ], 4 ]
15 = [ "comp_7->comp_8", [ 2, 2 ], 4 ]
13 = [ "comp_6->comp_0", [ 2, 2 ], 4 ]
14 = [ "comp_7->comp_0", [ 2, 2 ], 4 ]
26 = [ "comp_13->comp_6", [ 2, 2 ], 4 ]
19 = [ "comp_9->comp_10", [ 2, 2 ], 4 ]
16 = [ "comp_8->comp_1", [ 2, 2 ], 4 ]
8 = [ "comp_4->comp_11", [ 2, 2 ], 4 ]
28 = [ "shim_14->mem_16", [ 2, 2 ], 4 ]
9 = [ "comp_4->comp_5", [ 2, 2 ], 4 ]
1 = [ "comp_0->comp_1", [ 2, 2 ], 4 ]
17 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
0 = [ "comp_0->comp_7", [ 2, 2 ], 4 ]
22 = [ "comp_11->comp_4", [ 2, 2 ], 4 ]
7 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
10 = [ "comp_5->comp_12", [ 2, 2 ], 4 ]
27 = [ "comp_13->comp_7", [ 2, 2 ], 4 ]
20 = [ "comp_10->comp_3", [ 2, 2 ], 4 ]
21 = [ "comp_10->comp_11", [ 2, 2 ], 4 ]
23 = [ "comp_11->comp_12", [ 2, 2 ], 4 ]
24 = [ "comp_12->comp_5", [ 2, 2 ], 4 ]
2 = [ "comp_1->comp_8", [ 2, 2 ], 4 ]
25 = [ "comp_12->comp_13", [ 2, 2 ], 4 ]
6 = [ "comp_3->comp_10", [ 2, 2 ], 4 ]
3 = [ "comp_1->comp_2", [ 2, 2 ], 4 ]
30 = [ "comp_6->mem_17", [ 2, 2 ], 4 ]

[linking]
link_0 = "28->29"
link_1 = "30->31"

[route]
5 = [ "neighbor_sharing", { comp_3 = [ "2,2" ] } ]
4 = [ "neighbor_sharing", { comp_9 = [ "2,2" ] } ]
31 = [ "circuit_switch", { shim_15 = [ "1,6", "0,6" ] } ]
18 = [ "neighbor_sharing", { comp_2 = [ "3,2" ] } ]
11 = [ "neighbor_sharing", { comp_6 = [ "2,5" ] } ]
12 = [ "neighbor_sharing", { comp_13 = [ "2,6" ] } ]
29 = [ "circuit_switch", { comp_7 = [ "1,0", "2,0", "3,0" ] } ]
15 = [ "neighbor_sharing", { comp_8 = [ "3,0" ] } ]
13 = [ "circuit_switch", { comp_0 = [ "2,6", "2,5", "2,4", "2,3", "2,2", "2,1", "2,0" ] } ]
14 = [ "neighbor_sharing", { comp_0 = [ "3,0" ] } ]
26 = [ "neighbor_sharing", { comp_6 = [ "3,6" ] } ]
19 = [ "neighbor_sharing", { comp_10 = [ "3,2" ] } ]
16 = [ "neighbor_sharing", { comp_1 = [ "3,1" ] } ]
8 = [ "neighbor_sharing", { comp_11 = [ "2,4" ] } ]
28 = [ "circuit_switch", { mem_16 = [ "0,0", "1,0" ] } ]
9 = [ "neighbor_sharing", { comp_5 = [ "2,4" ] } ]
1 = [ "neighbor_sharing", { comp_1 = [ "2,0" ] } ]
17 = [ "neighbor_sharing", { comp_9 = [ "3,1" ] } ]
0 = [ "neighbor_sharing", { comp_7 = [ "2,0" ] } ]
22 = [ "neighbor_sharing", { comp_4 = [ "3,4" ] } ]
7 = [ "neighbor_sharing", { comp_4 = [ "2,3" ] } ]
10 = [ "neighbor_sharing", { comp_12 = [ "2,5" ] } ]
27 = [ "circuit_switch", { comp_7 = [ "3,6", "3,5", "3,4", "3,3", "3,2", "3,1", "3,0" ] } ]
20 = [ "neighbor_sharing", { comp_3 = [ "3,3" ] } ]
21 = [ "neighbor_sharing", { comp_11 = [ "3,3" ] } ]
23 = [ "neighbor_sharing", { comp_12 = [ "3,4" ] } ]
24 = [ "neighbor_sharing", { comp_5 = [ "3,5" ] } ]
2 = [ "neighbor_sharing", { comp_8 = [ "2,1" ] } ]
25 = [ "neighbor_sharing", { comp_13 = [ "3,5" ] } ]
6 = [ "neighbor_sharing", { comp_10 = [ "2,3" ] } ]
3 = [ "neighbor_sharing", { comp_2 = [ "2,1" ] } ]
30 = [ "circuit_switch", { mem_17 = [ "2,6", "1,6" ] } ]
