[node]
shim_18 = "0,7"
mem_19 = "1,7"
comp_2 = "2,2"
comp_6 = "2,6"
comp_5 = "2,5"
comp_14 = "3,6"
comp_7 = "2,7"
comp_1 = "2,1"
comp_9 = "3,1"
comp_12 = "3,4"
comp_15 = "3,7"
comp_8 = "3,0"
comp_4 = "2,4"
comp_0 = "2,0"
comp_3 = "2,3"
mem_17 = "1,0"
shim_16 = "0,0"
comp_10 = "3,2"
comp_11 = "3,3"
comp_13 = "3,5"

[edge]
2 = [ "comp_1->comp_0", [ 2, 2 ], 4 ]
19 = [ "comp_0->comp_15", [ 2, 2 ], 4 ]
6 = [ "comp_5->comp_2", [ 2, 2 ], 4 ]
17 = [ "mem_19->comp_15", [ 2, 2 ], 4 ]
7 = [ "comp_6->comp_2", [ 2, 2 ], 4 ]
16 = [ "shim_18->mem_19", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_0", [ 2, 2 ], 4 ]
8 = [ "comp_7->comp_3", [ 2, 2 ], 4 ]
5 = [ "comp_4->comp_1", [ 2, 2 ], 4 ]
4 = [ "comp_3->comp_1", [ 2, 2 ], 4 ]
10 = [ "comp_9->comp_4", [ 2, 2 ], 4 ]
1 = [ "mem_17->shim_16", [ 2, 2 ], 4 ]
0 = [ "comp_0->mem_17", [ 2, 2 ], 4 ]
9 = [ "comp_8->comp_3", [ 2, 2 ], 4 ]
18 = [ "comp_15->comp_7,comp_8,comp_9,comp_10,comp_11,comp_12,comp_13,comp_14", [ 2, 2, 2, 2, 2, 2, 2, 2, 2 ], 4 ]
11 = [ "comp_10->comp_4", [ 2, 2 ], 4 ]
12 = [ "comp_11->comp_5", [ 2, 2 ], 4 ]
15 = [ "comp_14->comp_6", [ 2, 2 ], 4 ]
13 = [ "comp_12->comp_5", [ 2, 2 ], 4 ]
14 = [ "comp_13->comp_6", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_1 = "16->17"

[route]
2 = [ "neighbor_sharing", { comp_0 = [ "2,0" ] } ]
19 = [ "circuit_switch", { comp_15 = [ "2,0", "3,0", "3,1", "3,2", "3,3", "3,4", "3,5", "3,6", "3,7" ] } ]
6 = [ "circuit_switch", { comp_2 = [ "2,5", "2,4", "2,3", "2,2" ] } ]
17 = [ "circuit_switch", { comp_15 = [ "1,7", "2,7", "3,7" ] } ]
7 = [ "circuit_switch", { comp_2 = [ "2,6", "2,5", "2,4", "2,3", "2,2" ] } ]
16 = [ "circuit_switch", { mem_19 = [ "0,7", "1,7" ] } ]
3 = [ "circuit_switch", { comp_0 = [ "2,2", "2,1", "2,0" ] } ]
8 = [ "circuit_switch", { comp_3 = [ "2,7", "2,6", "2,5", "2,4", "2,3" ] } ]
5 = [ "circuit_switch", { comp_1 = [ "2,4", "2,3", "2,2", "2,1" ] } ]
4 = [ "circuit_switch", { comp_1 = [ "2,3", "2,2", "2,1" ] } ]
10 = [ "circuit_switch", { comp_4 = [ "3,1", "3,2", "3,3", "3,4", "2,4" ] } ]
1 = [ "circuit_switch", { shim_16 = [ "1,0", "0,0" ] } ]
0 = [ "circuit_switch", { mem_17 = [ "2,0", "1,0" ] } ]
9 = [ "circuit_switch", { comp_3 = [ "3,0", "3,1", "3,2", "3,3", "2,3" ] } ]
18 = [ "circuit_switch", { comp_7 = [ "3,7", "2,7" ], comp_11 = [ "3,7", "3,6", "3,5", "3,4", "3,3" ], comp_8 = [ "3,7", "3,6", "3,5", "3,4", "3,3", "3,2", "3,1", "3,0" ], comp_10 = [ "3,7", "3,6", "3,5", "3,4", "3,3", "3,2" ], comp_9 = [ "3,7", "3,6", "3,5", "3,4", "3,3", "3,2", "3,1" ], comp_12 = [ "3,7", "3,6", "3,5", "3,4" ], comp_13 = [ "3,7", "3,6", "3,5" ], comp_14 = [ "3,7", "3,6" ] } ]
11 = [ "circuit_switch", { comp_4 = [ "3,2", "3,3", "3,4", "2,4" ] } ]
12 = [ "circuit_switch", { comp_5 = [ "3,3", "3,4", "3,5", "2,5" ] } ]
15 = [ "neighbor_sharing", { comp_6 = [ "2,6" ] } ]
13 = [ "circuit_switch", { comp_5 = [ "3,4", "3,5", "2,5" ] } ]
14 = [ "circuit_switch", { comp_6 = [ "3,5", "3,6", "2,6" ] } ]
