[node]
comp_17 = "4,3"
comp_12 = "3,5"
comp_1 = "2,1"
comp_16 = "4,2"
comp_13 = "3,6"
comp_6 = "2,6"
comp_8 = "3,1"
comp_15 = "4,1"
comp_5 = "2,5"
shim_22 = "0,6"
comp_0 = "2,0"
comp_20 = "4,6"
comp_4 = "2,4"
comp_9 = "3,2"
comp_11 = "3,4"
comp_3 = "2,3"
comp_7 = "3,0"
comp_2 = "2,2"
comp_18 = "4,4"
mem_23 = "1,0"
shim_21 = "0,0"
comp_10 = "3,3"
comp_19 = "4,5"
mem_24 = "1,6"
comp_14 = "4,0"

[edge]
34 = [ "comp_17->comp_3", [ 2, 2 ], 4 ]
14 = [ "comp_7->comp_14", [ 2, 2 ], 4 ]
33 = [ "comp_16->comp_17", [ 2, 2 ], 4 ]
31 = [ "comp_15->comp_16", [ 2, 2 ], 4 ]
32 = [ "comp_16->comp_2", [ 2, 2 ], 4 ]
26 = [ "comp_13->comp_20", [ 2, 2 ], 4 ]
30 = [ "comp_15->comp_1", [ 2, 2 ], 4 ]
3 = [ "comp_1->comp_2", [ 2, 2 ], 4 ]
45 = [ "mem_24->shim_22", [ 2, 2 ], 4 ]
6 = [ "comp_3->comp_10", [ 2, 2 ], 4 ]
25 = [ "comp_12->comp_13", [ 2, 2 ], 4 ]
2 = [ "comp_1->comp_8", [ 2, 2 ], 4 ]
24 = [ "comp_12->comp_19", [ 2, 2 ], 4 ]
23 = [ "comp_11->comp_12", [ 2, 2 ], 4 ]
21 = [ "comp_10->comp_11", [ 2, 2 ], 4 ]
20 = [ "comp_10->comp_17", [ 2, 2 ], 4 ]
13 = [ "comp_6->comp_0", [ 2, 2 ], 4 ]
15 = [ "comp_7->comp_8", [ 2, 2 ], 4 ]
29 = [ "comp_14->comp_15", [ 2, 2 ], 4 ]
42 = [ "shim_21->mem_23", [ 2, 2 ], 4 ]
19 = [ "comp_9->comp_10", [ 2, 2 ], 4 ]
37 = [ "comp_18->comp_19", [ 2, 2 ], 4 ]
38 = [ "comp_19->comp_5", [ 2, 2 ], 4 ]
8 = [ "comp_4->comp_11", [ 2, 2 ], 4 ]
4 = [ "comp_2->comp_9", [ 2, 2 ], 4 ]
43 = [ "mem_23->comp_7", [ 2, 2 ], 4 ]
5 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
16 = [ "comp_8->comp_15", [ 2, 2 ], 4 ]
41 = [ "comp_20->comp_14", [ 2, 2 ], 4 ]
28 = [ "comp_14->comp_0", [ 2, 2 ], 4 ]
10 = [ "comp_5->comp_12", [ 2, 2 ], 4 ]
7 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
9 = [ "comp_4->comp_5", [ 2, 2 ], 4 ]
36 = [ "comp_18->comp_4", [ 2, 2 ], 4 ]
1 = [ "comp_0->comp_1", [ 2, 2 ], 4 ]
40 = [ "comp_20->comp_6", [ 2, 2 ], 4 ]
17 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
0 = [ "comp_0->comp_7", [ 2, 2 ], 4 ]
22 = [ "comp_11->comp_18", [ 2, 2 ], 4 ]
44 = [ "comp_6->mem_24", [ 2, 2 ], 4 ]
12 = [ "comp_6->comp_13", [ 2, 2 ], 4 ]
39 = [ "comp_19->comp_20", [ 2, 2 ], 4 ]
11 = [ "comp_5->comp_6", [ 2, 2 ], 4 ]
18 = [ "comp_9->comp_16", [ 2, 2 ], 4 ]
27 = [ "comp_13->comp_7", [ 2, 2 ], 4 ]
35 = [ "comp_17->comp_18", [ 2, 2 ], 4 ]

[linking]
link_0 = "42->43"
link_1 = "44->45"

[route]
34 = [ "circuit_switch", { comp_3 = [ "4,3", "3,3", "2,3" ] } ]
14 = [ "neighbor_sharing", { comp_14 = [ "3,0" ] } ]
33 = [ "neighbor_sharing", { comp_17 = [ "4,2" ] } ]
31 = [ "neighbor_sharing", { comp_16 = [ "4,1" ] } ]
32 = [ "circuit_switch", { comp_2 = [ "4,2", "3,2", "2,2" ] } ]
26 = [ "neighbor_sharing", { comp_20 = [ "3,6" ] } ]
30 = [ "circuit_switch", { comp_1 = [ "4,1", "3,1", "2,1" ] } ]
3 = [ "neighbor_sharing", { comp_2 = [ "2,1" ] } ]
45 = [ "circuit_switch", { shim_22 = [ "1,6", "0,6" ] } ]
6 = [ "neighbor_sharing", { comp_10 = [ "2,3" ] } ]
25 = [ "neighbor_sharing", { comp_13 = [ "3,5" ] } ]
2 = [ "neighbor_sharing", { comp_8 = [ "2,1" ] } ]
24 = [ "neighbor_sharing", { comp_19 = [ "3,5" ] } ]
23 = [ "neighbor_sharing", { comp_12 = [ "3,4" ] } ]
21 = [ "neighbor_sharing", { comp_11 = [ "3,3" ] } ]
20 = [ "neighbor_sharing", { comp_17 = [ "3,3" ] } ]
13 = [ "circuit_switch", { comp_0 = [ "2,6", "2,5", "2,4", "2,3", "2,2", "2,1", "2,0" ] } ]
15 = [ "neighbor_sharing", { comp_8 = [ "3,0" ] } ]
29 = [ "neighbor_sharing", { comp_15 = [ "4,0" ] } ]
42 = [ "circuit_switch", { mem_23 = [ "0,0", "1,0" ] } ]
19 = [ "neighbor_sharing", { comp_10 = [ "3,2" ] } ]
37 = [ "neighbor_sharing", { comp_19 = [ "4,4" ] } ]
38 = [ "circuit_switch", { comp_5 = [ "4,5", "3,5", "2,5" ] } ]
8 = [ "neighbor_sharing", { comp_11 = [ "2,4" ] } ]
4 = [ "neighbor_sharing", { comp_9 = [ "2,2" ] } ]
43 = [ "circuit_switch", { comp_7 = [ "1,0", "2,0", "3,0" ] } ]
5 = [ "neighbor_sharing", { comp_3 = [ "2,2" ] } ]
16 = [ "neighbor_sharing", { comp_15 = [ "3,1" ] } ]
41 = [ "circuit_switch", { comp_14 = [ "4,6", "4,5", "4,4", "4,3", "4,2", "4,1", "4,0" ] } ]
28 = [ "circuit_switch", { comp_0 = [ "4,0", "3,0", "2,0" ] } ]
10 = [ "neighbor_sharing", { comp_12 = [ "2,5" ] } ]
7 = [ "neighbor_sharing", { comp_4 = [ "2,3" ] } ]
9 = [ "neighbor_sharing", { comp_5 = [ "2,4" ] } ]
36 = [ "circuit_switch", { comp_4 = [ "4,4", "3,4", "2,4" ] } ]
1 = [ "neighbor_sharing", { comp_1 = [ "2,0" ] } ]
40 = [ "circuit_switch", { comp_6 = [ "4,6", "3,6", "2,6" ] } ]
17 = [ "neighbor_sharing", { comp_9 = [ "3,1" ] } ]
0 = [ "neighbor_sharing", { comp_7 = [ "2,0" ] } ]
22 = [ "neighbor_sharing", { comp_18 = [ "3,4" ] } ]
44 = [ "circuit_switch", { mem_24 = [ "2,6", "1,6" ] } ]
12 = [ "neighbor_sharing", { comp_13 = [ "2,6" ] } ]
39 = [ "neighbor_sharing", { comp_20 = [ "4,5" ] } ]
11 = [ "neighbor_sharing", { comp_6 = [ "2,5" ] } ]
18 = [ "neighbor_sharing", { comp_16 = [ "3,2" ] } ]
27 = [ "circuit_switch", { comp_7 = [ "3,6", "3,5", "3,4", "3,3", "3,2", "3,1", "3,0" ] } ]
35 = [ "neighbor_sharing", { comp_18 = [ "4,3" ] } ]
