[node]
shim_16 = "0,0"
mem_19 = "1,7"
comp_13 = "3,5"
comp_11 = "3,3"
comp_1 = "2,1"
comp_5 = "2,5"
comp_0 = "2,0"
comp_4 = "2,4"
comp_12 = "3,4"
shim_17 = "0,7"
comp_9 = "3,1"
comp_3 = "2,3"
comp_7 = "2,7"
comp_2 = "2,2"
comp_10 = "3,2"
mem_18 = "1,0"
comp_6 = "2,6"
comp_14 = "3,6"
comp_8 = "3,0"
comp_15 = "3,7"

[edge]
34 = [ "comp_7->mem_19", [ 2, 2 ], 4 ]
14 = [ "comp_7->comp_15", [ 2, 2 ], 4 ]
33 = [ "mem_18->comp_8", [ 2, 2 ], 4 ]
31 = [ "comp_15->comp_8", [ 2, 2 ], 4 ]
32 = [ "shim_16->mem_18", [ 2, 2 ], 4 ]
26 = [ "comp_13->comp_5", [ 2, 2 ], 4 ]
11 = [ "comp_5->comp_6", [ 2, 2 ], 4 ]
18 = [ "comp_9->comp_1", [ 2, 2 ], 4 ]
12 = [ "comp_6->comp_14", [ 2, 2 ], 4 ]
29 = [ "comp_14->comp_15", [ 2, 2 ], 4 ]
15 = [ "comp_7->comp_0", [ 2, 2 ], 4 ]
13 = [ "comp_6->comp_7", [ 2, 2 ], 4 ]
19 = [ "comp_9->comp_10", [ 2, 2 ], 4 ]
4 = [ "comp_2->comp_10", [ 2, 2 ], 4 ]
5 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
16 = [ "comp_8->comp_0", [ 2, 2 ], 4 ]
30 = [ "comp_15->comp_7", [ 2, 2 ], 4 ]
6 = [ "comp_3->comp_11", [ 2, 2 ], 4 ]
3 = [ "comp_1->comp_2", [ 2, 2 ], 4 ]
8 = [ "comp_4->comp_12", [ 2, 2 ], 4 ]
28 = [ "comp_14->comp_6", [ 2, 2 ], 4 ]
9 = [ "comp_4->comp_5", [ 2, 2 ], 4 ]
1 = [ "comp_0->comp_1", [ 2, 2 ], 4 ]
17 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
0 = [ "comp_0->comp_8", [ 2, 2 ], 4 ]
22 = [ "comp_11->comp_3", [ 2, 2 ], 4 ]
7 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
10 = [ "comp_5->comp_13", [ 2, 2 ], 4 ]
27 = [ "comp_13->comp_14", [ 2, 2 ], 4 ]
35 = [ "mem_19->shim_17", [ 2, 2 ], 4 ]
20 = [ "comp_10->comp_2", [ 2, 2 ], 4 ]
21 = [ "comp_10->comp_11", [ 2, 2 ], 4 ]
23 = [ "comp_11->comp_12", [ 2, 2 ], 4 ]
24 = [ "comp_12->comp_4", [ 2, 2 ], 4 ]
2 = [ "comp_1->comp_9", [ 2, 2 ], 4 ]
25 = [ "comp_12->comp_13", [ 2, 2 ], 4 ]

[linking]
link_0 = "32->33"
link_1 = "34->35"

[route]
34 = [ "circuit_switch", { mem_19 = [ "2,7", "1,7" ] } ]
14 = [ "neighbor_sharing", { comp_15 = [ "2,7" ] } ]
33 = [ "circuit_switch", { comp_8 = [ "1,0", "2,0", "3,0" ] } ]
31 = [ "circuit_switch", { comp_8 = [ "3,7", "3,6", "3,5", "3,4", "3,3", "3,2", "3,1", "3,0" ] } ]
32 = [ "circuit_switch", { mem_18 = [ "0,0", "1,0" ] } ]
26 = [ "neighbor_sharing", { comp_5 = [ "3,5" ] } ]
11 = [ "neighbor_sharing", { comp_6 = [ "2,5" ] } ]
18 = [ "neighbor_sharing", { comp_1 = [ "3,1" ] } ]
12 = [ "neighbor_sharing", { comp_14 = [ "2,6" ] } ]
29 = [ "neighbor_sharing", { comp_15 = [ "3,6" ] } ]
15 = [ "circuit_switch", { comp_0 = [ "2,7", "2,6", "2,5", "2,4", "2,3", "2,2", "2,1", "2,0" ] } ]
13 = [ "neighbor_sharing", { comp_7 = [ "2,6" ] } ]
19 = [ "neighbor_sharing", { comp_10 = [ "3,1" ] } ]
4 = [ "neighbor_sharing", { comp_10 = [ "2,2" ] } ]
5 = [ "neighbor_sharing", { comp_3 = [ "2,2" ] } ]
16 = [ "neighbor_sharing", { comp_0 = [ "3,0" ] } ]
30 = [ "neighbor_sharing", { comp_7 = [ "3,7" ] } ]
6 = [ "neighbor_sharing", { comp_11 = [ "2,3" ] } ]
3 = [ "neighbor_sharing", { comp_2 = [ "2,1" ] } ]
8 = [ "neighbor_sharing", { comp_12 = [ "2,4" ] } ]
28 = [ "neighbor_sharing", { comp_6 = [ "3,6" ] } ]
9 = [ "neighbor_sharing", { comp_5 = [ "2,4" ] } ]
1 = [ "neighbor_sharing", { comp_1 = [ "2,0" ] } ]
17 = [ "neighbor_sharing", { comp_9 = [ "3,0" ] } ]
0 = [ "neighbor_sharing", { comp_8 = [ "2,0" ] } ]
22 = [ "neighbor_sharing", { comp_3 = [ "3,3" ] } ]
7 = [ "neighbor_sharing", { comp_4 = [ "2,3" ] } ]
10 = [ "neighbor_sharing", { comp_13 = [ "2,5" ] } ]
27 = [ "neighbor_sharing", { comp_14 = [ "3,5" ] } ]
35 = [ "circuit_switch", { shim_17 = [ "1,7", "0,7" ] } ]
20 = [ "neighbor_sharing", { comp_2 = [ "3,2" ] } ]
21 = [ "neighbor_sharing", { comp_11 = [ "3,2" ] } ]
23 = [ "neighbor_sharing", { comp_12 = [ "3,3" ] } ]
24 = [ "neighbor_sharing", { comp_4 = [ "3,4" ] } ]
2 = [ "neighbor_sharing", { comp_9 = [ "2,1" ] } ]
25 = [ "neighbor_sharing", { comp_13 = [ "3,4" ] } ]
