[node]
comp_2 = "4,0"
shim_4 = "0,0"
comp_1 = "3,0"
mem_5 = "1,0"
comp_0 = "2,0"
comp_3 = "5,0"

[edge]
0 = [ "comp_0->mem_5", [ 2, 2 ], 4 ]
1 = [ "mem_5->shim_4", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_0", [ 2, 2 ], 4 ]
5 = [ "mem_5->comp_3", [ 2, 2 ], 4 ]
2 = [ "comp_1->comp_0", [ 2, 2 ], 4 ]
4 = [ "shim_4->mem_5", [ 2, 2 ], 4 ]
6 = [ "comp_3->comp_1,comp_2", [ 2, 2, 2 ], 4 ]
7 = [ "comp_0->comp_3", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_1 = "4->5"

[route]
0 = [ "circuit_switch", { mem_5 = [ "2,0", "1,0" ] } ]
1 = [ "circuit_switch", { shim_4 = [ "1,0", "0,0" ] } ]
3 = [ "circuit_switch", { comp_0 = [ "4,0", "3,0", "2,0" ] } ]
5 = [ "circuit_switch", { comp_3 = [ "1,0", "2,0", "3,0", "4,0", "5,0" ] } ]
2 = [ "neighbor_sharing", { comp_0 = [ "3,0" ] } ]
4 = [ "circuit_switch", { mem_5 = [ "0,0", "1,0" ] } ]
6 = [ "circuit_switch", { comp_1 = [ "5,0", "4,0", "3,0" ], comp_2 = [ "5,0", "4,0" ] } ]
7 = [ "circuit_switch", { comp_3 = [ "2,0", "3,0", "4,0", "5,0" ] } ]
