[node]
comp_7 = "5,2"
comp_17 = "4,4"
comp_14 = "3,7"
comp_13 = "4,7"
comp_12 = "5,7"
comp_18 = "4,3"
comp_19 = "4,2"
comp_2 = "2,0"
comp_16 = "4,5"
mem_1 = "1,0"
comp_9 = "5,4"
comp_15 = "4,6"
comp_8 = "5,3"
comp_5 = "5,0"
comp_6 = "5,1"
comp_3 = "3,0"
comp_21 = "3,1"
shim_24 = "0,1"
mem_23 = "1,1"
comp_22 = "2,1"
comp_4 = "4,0"
comp_20 = "4,1"
shim_0 = "0,0"
comp_11 = "5,6"
comp_10 = "5,5"

[edge]
2 = [ "comp_2->comp_3", [ 2, 2 ], 1024 ]
19 = [ "comp_19->comp_20", [ 2, 2 ], 1024 ]
6 = [ "comp_6->comp_7", [ 2, 2 ], 1024 ]
17 = [ "comp_17->comp_18", [ 2, 2 ], 1024 ]
7 = [ "comp_7->comp_8", [ 2, 2 ], 1024 ]
16 = [ "comp_16->comp_17", [ 2, 2 ], 1024 ]
3 = [ "comp_3->comp_4", [ 2, 2 ], 1024 ]
14 = [ "comp_14->comp_15", [ 2, 2 ], 1024 ]
13 = [ "comp_13->comp_14", [ 2, 2 ], 1024 ]
15 = [ "comp_15->comp_16", [ 2, 2 ], 1024 ]
12 = [ "comp_12->comp_13", [ 2, 2 ], 1024 ]
8 = [ "comp_8->comp_9", [ 2, 2 ], 1024 ]
5 = [ "comp_5->comp_6", [ 2, 2 ], 1024 ]
11 = [ "comp_11->comp_12", [ 2, 2 ], 1024 ]
18 = [ "comp_18->comp_19", [ 2, 2 ], 1024 ]
4 = [ "comp_4->comp_5", [ 2, 2 ], 1024 ]
24 = [ "comp_21->comp_3", [ 2, 2 ], 1024 ]
23 = [ "mem_23->shim_24", [ 2, 2 ], 1024 ]
21 = [ "comp_21->comp_22", [ 2, 2 ], 1024 ]
20 = [ "comp_20->comp_21", [ 2, 2 ], 1024 ]
10 = [ "comp_10->comp_11", [ 2, 2 ], 1024 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 1024 ]
22 = [ "comp_22->mem_23", [ 2, 2 ], 1024 ]
0 = [ "shim_0->mem_1", [ 2, 2 ], 1024 ]
9 = [ "comp_9->comp_10", [ 2, 2 ], 1024 ]

[linking]
link_0 = "0->1"
link_1 = "22->23"

[route]
2 = [ "neighbor_sharing", { comp_3 = [ "2,0" ] } ]
19 = [ "neighbor_sharing", { comp_20 = [ "4,1" ] } ]
6 = [ "neighbor_sharing", { comp_7 = [ "5,1" ] } ]
17 = [ "neighbor_sharing", { comp_18 = [ "4,3" ] } ]
7 = [ "neighbor_sharing", { comp_8 = [ "5,2" ] } ]
16 = [ "neighbor_sharing", { comp_17 = [ "4,4" ] } ]
3 = [ "neighbor_sharing", { comp_4 = [ "3,0" ] } ]
14 = [ "circuit_switch", { comp_15 = [ "3,7", "3,6", "4,6" ] } ]
13 = [ "neighbor_sharing", { comp_14 = [ "4,7" ] } ]
15 = [ "neighbor_sharing", { comp_16 = [ "4,5" ] } ]
12 = [ "neighbor_sharing", { comp_13 = [ "4,7" ] } ]
8 = [ "neighbor_sharing", { comp_9 = [ "5,3" ] } ]
5 = [ "neighbor_sharing", { comp_6 = [ "5,0" ] } ]
11 = [ "neighbor_sharing", { comp_12 = [ "5,6" ] } ]
18 = [ "neighbor_sharing", { comp_19 = [ "4,2" ] } ]
4 = [ "neighbor_sharing", { comp_5 = [ "4,0" ] } ]
24 = [ "neighbor_sharing", { comp_3 = [ "3,0" ] } ]
23 = [ "circuit_switch", { shim_24 = [ "1,1", "0,1" ] } ]
21 = [ "neighbor_sharing", { comp_22 = [ "3,1" ] } ]
20 = [ "neighbor_sharing", { comp_21 = [ "4,1" ] } ]
10 = [ "neighbor_sharing", { comp_11 = [ "5,5" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
22 = [ "circuit_switch", { mem_23 = [ "2,1", "1,1" ] } ]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
9 = [ "neighbor_sharing", { comp_10 = [ "5,4" ] } ]
