[node]
shim_0 = "0,0"
mem_1 = "1,0"
comp_2 = "2,0"
comp_4 = "4,0"
comp_5 = "4,1"
mem_8 = "1,1"
shim_9 = "0,1"
comp_6 = "3,1"
comp_7 = "2,1"
comp_3 = "3,0"

[edge]
0 = [ "shim_0->mem_1", [ 2, 2 ], 1024 ]
1 = [ "mem_1->comp_2", [ 2, 2 ], 1024 ]
3 = [ "comp_3->comp_4", [ 2, 2 ], 1024 ]
5 = [ "comp_5->comp_6", [ 2, 2 ], 1024 ]
2 = [ "comp_2->comp_3", [ 2, 2 ], 1024 ]
4 = [ "comp_4->comp_5", [ 2, 2 ], 1024 ]
6 = [ "comp_6->comp_7", [ 2, 2 ], 1024 ]
7 = [ "comp_7->mem_8", [ 2, 2 ], 1024 ]
8 = [ "mem_8->shim_9", [ 2, 2 ], 1024 ]
9 = [ "comp_6->comp_3", [ 2, 2 ], 1024 ]

[linking]
link_0 = "0->1"
link_1 = "7->8"

[route]
0 = [ "circuit_switch", { mem_1 = [ "0,0", "1,0" ] } ]
1 = [ "circuit_switch", { comp_2 = [ "1,0", "2,0" ] } ]
3 = [ "neighbor_sharing", { comp_4 = [ "3,0" ] } ]
5 = [ "neighbor_sharing", { comp_6 = [ "4,1" ] } ]
2 = [ "neighbor_sharing", { comp_3 = [ "2,0" ] } ]
4 = [ "neighbor_sharing", { comp_5 = [ "4,0" ] } ]
6 = [ "neighbor_sharing", { comp_7 = [ "3,1" ] } ]
7 = [ "circuit_switch", { mem_8 = [ "2,1", "1,1" ] } ]
8 = [ "circuit_switch", { shim_9 = [ "1,1", "0,1" ] } ]
9 = [ "neighbor_sharing", { comp_3 = [ "3,0" ] } ]
