[node]
shim_16 = "0,4"
comp_1 = "2,1"
comp_11 = "4,1"
comp_5 = "3,0"
comp_8 = "3,3"
comp_0 = "2,0"
comp_4 = "2,4"
comp_9 = "3,4"
comp_12 = "4,2"
mem_17 = "1,0"
comp_3 = "2,3"
comp_7 = "3,2"
comp_2 = "2,2"
comp_14 = "4,4"
mem_18 = "1,4"
comp_6 = "3,1"
comp_13 = "4,3"
shim_15 = "0,0"
comp_10 = "4,0"

[edge]
4 = [ "comp_2->comp_7", [ 2, 2 ], 4 ]
33 = [ "mem_18->shim_16", [ 2, 2 ], 4 ]
31 = [ "mem_17->comp_5", [ 2, 2 ], 4 ]
32 = [ "comp_4->mem_18", [ 2, 2 ], 4 ]
26 = [ "comp_13->comp_3", [ 2, 2 ], 4 ]
11 = [ "comp_5->comp_6", [ 2, 2 ], 4 ]
18 = [ "comp_9->comp_14", [ 2, 2 ], 4 ]
12 = [ "comp_6->comp_11", [ 2, 2 ], 4 ]
29 = [ "comp_14->comp_10", [ 2, 2 ], 4 ]
15 = [ "comp_7->comp_8", [ 2, 2 ], 4 ]
13 = [ "comp_6->comp_7", [ 2, 2 ], 4 ]
14 = [ "comp_7->comp_12", [ 2, 2 ], 4 ]
19 = [ "comp_9->comp_5", [ 2, 2 ], 4 ]
5 = [ "comp_2->comp_3", [ 2, 2 ], 4 ]
16 = [ "comp_8->comp_13", [ 2, 2 ], 4 ]
8 = [ "comp_4->comp_9", [ 2, 2 ], 4 ]
28 = [ "comp_14->comp_4", [ 2, 2 ], 4 ]
9 = [ "comp_4->comp_0", [ 2, 2 ], 4 ]
1 = [ "comp_0->comp_1", [ 2, 2 ], 4 ]
17 = [ "comp_8->comp_9", [ 2, 2 ], 4 ]
0 = [ "comp_0->comp_5", [ 2, 2 ], 4 ]
22 = [ "comp_11->comp_1", [ 2, 2 ], 4 ]
7 = [ "comp_3->comp_4", [ 2, 2 ], 4 ]
10 = [ "comp_5->comp_10", [ 2, 2 ], 4 ]
27 = [ "comp_13->comp_14", [ 2, 2 ], 4 ]
20 = [ "comp_10->comp_0", [ 2, 2 ], 4 ]
21 = [ "comp_10->comp_11", [ 2, 2 ], 4 ]
23 = [ "comp_11->comp_12", [ 2, 2 ], 4 ]
24 = [ "comp_12->comp_2", [ 2, 2 ], 4 ]
2 = [ "comp_1->comp_6", [ 2, 2 ], 4 ]
25 = [ "comp_12->comp_13", [ 2, 2 ], 4 ]
6 = [ "comp_3->comp_8", [ 2, 2 ], 4 ]
3 = [ "comp_1->comp_2", [ 2, 2 ], 4 ]
30 = [ "shim_15->mem_17", [ 2, 2 ], 4 ]

[linking]
link_0 = "30->31"
link_1 = "32->33"

[route]
4 = [ "neighbor_sharing", { comp_7 = [ "2,2" ] } ]
33 = [ "circuit_switch", { shim_16 = [ "1,4", "0,4" ] } ]
31 = [ "circuit_switch", { comp_5 = [ "1,0", "2,0", "3,0" ] } ]
32 = [ "circuit_switch", { mem_18 = [ "2,4", "1,4" ] } ]
26 = [ "circuit_switch", { comp_3 = [ "4,3", "3,3", "2,3" ] } ]
11 = [ "neighbor_sharing", { comp_6 = [ "3,0" ] } ]
18 = [ "neighbor_sharing", { comp_14 = [ "3,4" ] } ]
12 = [ "neighbor_sharing", { comp_11 = [ "3,1" ] } ]
29 = [ "circuit_switch", { comp_10 = [ "4,4", "4,3", "4,2", "4,1", "4,0" ] } ]
15 = [ "neighbor_sharing", { comp_8 = [ "3,2" ] } ]
13 = [ "neighbor_sharing", { comp_7 = [ "3,1" ] } ]
14 = [ "neighbor_sharing", { comp_12 = [ "3,2" ] } ]
19 = [ "circuit_switch", { comp_5 = [ "3,4", "3,3", "3,2", "3,1", "3,0" ] } ]
5 = [ "neighbor_sharing", { comp_3 = [ "2,2" ] } ]
16 = [ "neighbor_sharing", { comp_13 = [ "3,3" ] } ]
8 = [ "neighbor_sharing", { comp_9 = [ "2,4" ] } ]
28 = [ "circuit_switch", { comp_4 = [ "4,4", "3,4", "2,4" ] } ]
9 = [ "circuit_switch", { comp_0 = [ "2,4", "2,3", "2,2", "2,1", "2,0" ] } ]
1 = [ "neighbor_sharing", { comp_1 = [ "2,0" ] } ]
17 = [ "neighbor_sharing", { comp_9 = [ "3,3" ] } ]
0 = [ "neighbor_sharing", { comp_5 = [ "3,0" ] } ]
22 = [ "circuit_switch", { comp_1 = [ "4,1", "3,1", "2,1" ] } ]
7 = [ "neighbor_sharing", { comp_4 = [ "2,3" ] } ]
10 = [ "neighbor_sharing", { comp_10 = [ "3,0" ] } ]
27 = [ "neighbor_sharing", { comp_14 = [ "4,3" ] } ]
20 = [ "circuit_switch", { comp_0 = [ "4,0", "3,0", "2,0" ] } ]
21 = [ "neighbor_sharing", { comp_11 = [ "4,0" ] } ]
23 = [ "neighbor_sharing", { comp_12 = [ "4,1" ] } ]
24 = [ "circuit_switch", { comp_2 = [ "4,2", "3,2", "2,2" ] } ]
2 = [ "neighbor_sharing", { comp_6 = [ "3,1" ] } ]
25 = [ "neighbor_sharing", { comp_13 = [ "4,2" ] } ]
6 = [ "neighbor_sharing", { comp_8 = [ "2,3" ] } ]
3 = [ "neighbor_sharing", { comp_2 = [ "2,1" ] } ]
30 = [ "circuit_switch", { mem_17 = [ "0,0", "1,0" ] } ]
