[node]
mem_6 = "1,0"
comp_1 = "2,1"
shim_7 = "0,4"
mem_8 = "1,4"
shim_5 = "0,0"
comp_3 = "2,3"
comp_2 = "2,2"
comp_0 = "2,0"
comp_4 = "2,4"

[edge]
0 = [ "comp_0->mem_6", [ 2, 2 ], 4 ]
1 = [ "mem_6->shim_5", [ 2, 2 ], 4 ]
3 = [ "comp_2->comp_0", [ 2, 2 ], 4 ]
5 = [ "shim_7->mem_8", [ 2, 2 ], 4 ]
2 = [ "comp_1->comp_0", [ 2, 2 ], 4 ]
4 = [ "comp_3->comp_1", [ 2, 2 ], 4 ]
6 = [ "mem_8->comp_4", [ 2, 2 ], 4 ]
7 = [ "comp_4->comp_2,comp_3", [ 2, 2, 2 ], 4 ]
8 = [ "comp_0->comp_4", [ 2, 2 ], 4 ]

[linking]
link_0 = "0->1"
link_1 = "5->6"

[route]
0 = [ "circuit_switch", { mem_6 = [ "2,0", "1,0" ] } ]
1 = [ "circuit_switch", { shim_5 = [ "1,0", "0,0" ] } ]
3 = [ "circuit_switch", { comp_0 = [ "2,2", "2,1", "2,0" ] } ]
5 = [ "circuit_switch", { mem_8 = [ "0,4", "1,4" ] } ]
2 = [ "neighbor_sharing", { comp_0 = [ "2,0" ] } ]
4 = [ "circuit_switch", { comp_1 = [ "2,3", "2,2", "2,1" ] } ]
6 = [ "circuit_switch", { comp_4 = [ "1,4", "2,4" ] } ]
7 = [ "circuit_switch", { comp_2 = [ "2,4", "2,3", "2,2" ], comp_3 = [ "2,4", "2,3" ] } ]
8 = [ "circuit_switch", { comp_4 = [ "2,0", "2,1", "2,2", "2,3", "2,4" ] } ]
